baseURL: /
buildDrafts: true
enableRobotsTXT: true
languageCode: en-us
publishDir: test
SectionPagesMenu: main
theme:
  - github.com/theNewDynamic/gohugo-theme-ananke
timeout: 60000
title: Wait What's That? (Development)
module:
  imports:
    - path: github.com/ApoorvSaxena/lozad.js
      mounts:
        - source: dist/lozad.js
          target: assets/lozad.js
    - path: github.com/dimsemenov/PhotoSwipe
      mounts:
        - source: dist
          target: assets/photoswipe
        - source: dist/default-skin/default-skin.png
          target: assets
