favicon = ""
site_logo = ""
description = "Two old folks travelling the world with no baggage"
mainSections = ["posts"]
facebook = ""
twitter = ""
instagram = ""
youtube = ""
github = ""
gitlab = ""
linkedin = ""
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""
# choose a background color from any on this page:
# http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-green"
featured_image = "/images/jizos.jpg"
# The theme is set, by default, to use a near-white background color
# and the "Avenir" or serif typeface.
body_classes = "avenir bg-washed-yellow"
# body_classes parameter will not change the font used in post
# content. To do this, you must use the post_content_classes
# parameter
recent_posts_number = 6
galleryLoadJQuery = true
