baseURL: https://staging.waitwhatsthat.com
buildDrafts: false
enableRobotsTXT: true
languageCode: en-us
publishDir: staging
SectionPagesMenu: main
theme:
  - github.com/theNewDynamic/gohugo-theme-ananke
timeout: 60000
title: Wait What's That? (Staging)
