baseURL = "/"
languageCode = "en-us"
title = "Wait What's That?"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
theme = ["github.com/theNewDynamic/gohugo-theme-ananke", "github.com/mfg92/hugo-shortcode-gallery"]
# resourceDir = "../resources"

# DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

# [languages]
#   [languages.en]
#     title = "My blog"
#     weight = 1
#     contentDir = "content/en"
#   [languages.fr]
#     title = "Mon blogue"
#     weight = 2
#     contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Two old folks travelling the world with no baggage"
  mainSections = ["posts"]
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page:
  # http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/jizos.jpg"
  # The theme is set, by default, to use a near-white background color
  # and the "Avenir" or serif typeface.
  body_classes = "avenir bg-washed-yellow"
  # body_classes parameter will not change the font used in post
  # content. To do this, you must use the post_content_classes
  # parameter
  recent_posts_number = 6
  galleryLoadJQuery = true
